#!/usr/bin/env bash
#read and cut

while read -r line; do
    # Extract the username, user id, and home directory path for each user
    username=$(echo "$line" | cut -d: -f1)
    uid=$(echo "$line" | cut -d: -f3)
    home=$(echo "$line" | cut -d: -f6)

    # Display the extracted information in the desired format
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
