#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 12 ]; do
    echo "$hour:00"
    hour=$((hour+1))
done

# Display minutes from 1 to 59
minute=1
while [ $minute -lt 60 ]; do
    echo "12:$minute"
    minute=$((minute+1))
done
